### PR TITLE
add themable (monochrome) icon

### PR DESCRIPTION
**Pull request by TinfoilSubmarine**
image

Thoughts? This is just the bare minimum, obviously we can add a modified version to use for this.

### CODE REVIEW

**Comment by x13a** [comment]
Looks good, but the circle doesnt have a `-` sign, like DND

**Comment by TinfoilSubmarine** [comment]
How about this?
image

**Comment by x13a** [comment]
Its perfect)

**Comment by TinfoilSubmarine** [comment]
My latest force-push has this one with the DND `-` line.

**Comment by x13a** [comment]
Thank you very much @TinfoilSubmarine 
Merging

**Pull request merged**
